### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by magj2006** [stopak/ICPunks#10]
there is missing icpunks_assets in dfx.json, so one error happend while running local_deploy.sh
<img width="611" alt="屏幕快照 2022-02-11 下午8 02 52" src="https://user-images.githubusercontent.com/8394789/153588391-6f53c978-e40a-4fd3-9886-e7177832d28f.png">

**Comment by stopak** [comment]
icpunks_assets contains icpunks website, it is not required to launch icpunks and icpunks_storage. Can you copy your build log?

**Comment by magj2006** [comment]
Yes，Please check below snapshot.
<img width="697" alt="屏幕快照 2022-02-11 下午10 37 17" src="https://user-images.githubusercontent.com/8394789/153611513-fba2ce51-80e0-4602-8e08-75f8098fcec8.png">

...
...

<img width="1019" alt="屏幕快照 2022-02-11 下午10 37 35" src="https://user-images.githubusercontent.com/8394789/153611548-2ccf0b0f-1252-4004-9a5a-30883c4e1141.png">

**Comment by magj2006** [comment]
Yes, Please check below snapshots.
<img width="687" alt="屏幕快照 2022-02-11 下午10 49 25" src="https://user-images.githubusercontent.com/8394789/153613512-b47ae36a-cffb-4850-a009-83a177ea58d4.png">

...
...

<img width="1029" alt="屏幕快照 2022-02-11 下午10 49 39" src="https://user-images.githubusercontent.com/8394789/153613563-64c968a0-059c-4fd4-926f-5d4100430acb.png">

**Comment by stopak** [comment]
Check if you have ic_cdk_optimizer it is necessary for rust canister to be deployed as canister. Try to run it, look if it shows any errors

**Comment by stopak** [comment]
Now it looks ok :) you have deployed locally icpunks canister

**Comment by magj2006** [comment]
but it outputs "Cannot find canister id. Please issue 'dfx canister create icpunks_assets'."

**Comment by magj2006** [comment]
Ok, I know how to do next, thank you.
